included:
  - fearless

excluded:
  - Pods
  - PrivatePods
  - SourcePackages
  - .build
  - Packages/FearlessBuildTools/.build
  - R.generated.swift
  - fearlessTests
  - fearlessIntegrationTests

baseline: .swiftlint-baseline.json
