comment:
  layout: "reach, diff, flags, files"
  behavior: default
  branches:
    - "develop"

ignore:
  - "**/*View.swift"
  - "**/*ViewController.swift"
  - "**/*Cell.swift"
  - "**/*Wireframe.swift"
