comment:
  layout: "reach, diff, flags, files"
  behavior: default
  branches:
    - "develop"

ignore:
  - "*View.swift"
  - "*ViewFactory.swift"
  - "*ViewController.swift"
  - "*Cell.swift"
  - "*Wireframe.swift"
