comment:
  layout: "reach, diff, flags, files"
  behavior: default
  branches:
    - "develop"

coverage:
  range: 40..90
  precision: 2
  round: down
  status:
    project:
      default:
        target: auto
        threshold: 1.0
        base: auto
    patch:
      default:
        target: auto
        threshold: 1.0
        base: auto

flag_management:
  default_rules:
    carryforward: true

ignore:
  - "**/*View.swift"
  - "**/*Factory.swift"
  - "**/*ViewController.swift"
  - "**/*Cell.swift"
  - "**/*Wireframe.swift"
  - "fearless/Common/Protocols"
  - "fearless/Common/View"
  - "fearless/Common/ViewController"
  - "docs/**"
